export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const SET_TOKEN = "SET_TOKEN"
export const SET_USER = "SET_USER"
export const SET_AUTH_ERROR = "SET_AUTH_ERROR"
export const LOGOUT = "LOGOUT"
