export const LOGIN = "LOGIN"
export const REGISTER = "REGISTER"
export const SET_TOKEN = "SET_TOKEN"
export const SET_USER = "SET_USER"
export const SET_AUTH_ERROR = "SET_AUTH_ERROR"
export const LOGOUT = "LOGOUT"
export const REFRESH_USER_INFO = "REFRESH_USER_INFO"

export const UPDATE_USER_INFO = "UPDATE_USER_INFO"

export const TO_EMAIL_VERIFICATION_MODE = "TO_EMAIL_VERIFICATION_MODE"
export const LEAVE_EMAIL_VERIFICATION_MODE = "LEAVE_EMAIL_VERIFICATION_MODE"

export const VERIFY_EMAIL = "VERIFY_EMAIL"
