export const CLEAR_SEARCH = "CLEAR_SEARCH"
export const SET_SEARCH_PARAMS = "SET_SEARCH_PARAMS"
export const OPEN_SEARCH_MODAL = "OPEN_SEARCH_MODAL"
export const CLOSE_SEARCH_MODAL = "CLOSE_SEARCH_MODAL"
