export const serverURL = "http://localhost:3000"
export const Mode = {
  REGISTER_POLITICIAN: "REGISTER_POLITICIAN",
  REGISTER_PHD: "REGISTER_PHD",
  LOGIN: "LOGIN"
}

export const ModalMode = {
  SEARCH_PROJECT: "SEARCH_PROJECT",
  SEARCH_USER: "SEARCH_USER",
  PROJECT_DETAILS: "PROJECT_DETAILS",
  USER_DETAILS: "USER_DETAILS"
}
